/* eslint-disable no-unused-vars */
const employees = [
  {
    id: 1,
    email: "employee1@example.com",
    password: "Kanhu@143",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Complete Project Report",
        description: "Prepare and submit the final report for the project.",
        date: "2024-11-04",
        categories: ["Documentation", "Project Management"],
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Team Meeting",
        description: "Attend and contribute to the weekly team meeting.",
        date: "2024-11-01",
        categories: ["Meeting", "Teamwork"],
      },
    ],
  },
  {
    id: 2,
    email: "employee2@example.com",
    password: "Kanhu@143",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Client Presentation",
        description: "Prepare slides and deliver the client presentation.",
        date: "2024-11-05",
        categories: ["Presentation", "Client Work"],
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Code Review",
        description: "Review code submitted by junior developers.",
        date: "2024-10-31",
        categories: ["Development", "Review"],
      },
    ],
  },
  {
    id: 3,
    email: "employee3@example.com",
    password: "Kanhu@143",
    tasks: [
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Database Optimization",
        description: "Optimize database queries to improve performance.",
        date: "2024-10-30",
        categories: ["Database", "Optimization"],
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Feature Implementation",
        description: "Develop and test new feature for the product.",
        date: "2024-11-06",
        categories: ["Development", "Feature"],
      },
    ],
  },
  {
    id: 4,
    email: "employee4@example.com",
    password: "Kanhu@143",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Bug Fixing",
        description: "Identify and fix critical bugs reported by QA.",
        date: "2024-11-03",
        categories: ["Debugging", "QA"],
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Server Migration",
        description: "Migrate the application to a new server.",
        date: "2024-10-29",
        categories: ["Infrastructure", "Migration"],
      },
    ],
  },
  {
    id: 5,
    email: "employee5@example.com",
    password: "Kanhu@143",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "User Feedback Analysis",
        description: "Analyze user feedback for the new release.",
        date: "2024-11-07",
        categories: ["Analysis", "Feedback"],
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Security Audit",
        description: "Perform a security audit on the new features.",
        date: "2024-10-28",
        categories: ["Security", "Audit"],
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@gmail.com",
    password: "Kanhu@143",
  },
];
